// <auto-generated />
using CodeFirstMigrationUpdates.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstMigrationUpdates.Migrations
{
    [DbContext(typeof(ShelfContext))]
    [Migration("20201101140610_Seed_ShelfMaterial")]
    partial class Seed_ShelfMaterial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFirstMigrationUpdates.Models.Shelf", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("ShelfMaterialID")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.HasIndex("ShelfMaterialID")
                        .HasName("FK_Shelf_ShelfMaterial");

                    b.ToTable("Shelf");
                });

            modelBuilder.Entity("CodeFirstMigrationUpdates.Models.ShelfMaterial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("Shelf_Material");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            MaterialName = "Concrete"
                        },
                        new
                        {
                            ID = -2,
                            MaterialName = "Marble"
                        },
                        new
                        {
                            ID = -3,
                            MaterialName = "Rock"
                        },
                        new
                        {
                            ID = -4,
                            MaterialName = "Ceramic"
                        },
                        new
                        {
                            ID = -5,
                            MaterialName = "Plastic"
                        });
                });

            modelBuilder.Entity("CodeFirstMigrationUpdates.Models.Shelf", b =>
                {
                    b.HasOne("CodeFirstMigrationUpdates.Models.ShelfMaterial", "ShelfMaterial")
                        .WithMany("Shelves")
                        .HasForeignKey("ShelfMaterialID")
                        .HasConstraintName("FK_Shelf_ShelfMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
